export const INTERESTS_BY_CATEGORY = [
  {
    title: "❤️ hobbies",
    tags: [
      { emoji: "📚", label: "Reading" },
      { emoji: "✍️", label: "Writing" },
      { emoji: "📸", label: "Photography" },
      { emoji: "🎬", label: "Content Creation" },
      { emoji: "✏️", label: "Drawing & Sketching" },
      { emoji: "🎨", label: "Graphic Design" },
      { emoji: "🍳", label: "Cooking & Baking" },
      { emoji: "☕", label: "Coffee Brewing" },
      { emoji: "✈️", label: "Traveling" },
      { emoji: "🥾", label: "Hiking & Trekking" },
      { emoji: "🏋️", label: "Gym & Fitness" },
      { emoji: "🧘", label: "Yoga & Meditation" },
      { emoji: "💃", label: "Dancing" },
      { emoji: "🎸", label: "Playing Instruments" },
      { emoji: "🎛️", label: "Music Production" },
      { emoji: "💻", label: "Coding & Tech" },
      { emoji: "👗", label: "Fashion & Styling" },
      { emoji: "🖋️", label: "Calligraphy" },
      { emoji: "♟️", label: "Chess & Board Games" },
      { emoji: "🌱", label: "Gardening" }
    ]
  },
  {
    title: "🎵 music",
    tags: [
      { emoji: "🎤", label: "Arijit Singh" },
      { emoji: "🎧", label: "AP Dhillon" },
      { emoji: "🔥", label: "Diljit Dosanjh" },
      { emoji: "🌈", label: "A.R. Rahman" },
      { emoji: "💖", label: "Taylor Swift" },
      { emoji: "🌌", label: "The Weeknd" },
      { emoji: "🪩", label: "Coldplay" },
      { emoji: "🎙️", label: "Shreya Ghoshal" },
      { emoji: "🎼", label: "KK" },
      { emoji: "🎧", label: "Atif Aslam" },
      { emoji: "💿", label: "Karan Aujla" },
      { emoji: "🤍", label: "Indie Pop" },
      { emoji: "🎶", label: "Pop" },
      { emoji: "🎸", label: "Rock" },
      { emoji: "🎵", label: "Hip-Hop & Rap" },
      { emoji: "🌙", label: "Lo-fi" },
      { emoji: "⚡", label: "EDM" },
      { emoji: "🪘", label: "Punjabi" },
      { emoji: "🎬", label: "Bollywood" },
      { emoji: "💜", label: "K-Pop" }
    ]
  },
  {
    title: "😎 chill",
    tags: [
      { emoji: "😌", label: "Laid Back" },
      { emoji: "🎯", label: "Locked In" },
      { emoji: "🌙", label: "Introvert" },
      { emoji: "☀️", label: "Extrovert" },
      { emoji: "⚖️", label: "Ambivert" },
      { emoji: "🌊", label: "Easygoing" },
      { emoji: "🌱", label: "Lowkey" },
      { emoji: "💤", label: "Homebody" },
      { emoji: "🥳", label: "Social Butterfly" },
      { emoji: "🚀", label: "Ambitious" },
      { emoji: "🌃", label: "Night Owl" },
      { emoji: "🌅", label: "Early Bird" },
      { emoji: "🎨", label: "Creative" },
      { emoji: "✨", label: "Dreamer" },
      { emoji: "😂", label: "Witty & Sarcastic" },
      { emoji: "🫡", label: "Good Listener" },
      { emoji: "🧃", label: "Go With The Flow" },
      { emoji: "🤠", label: "Chaotic Good" },
      { emoji: "🌈", label: "Optimistic" },
      { emoji: "🛋️", label: "Chill Vibes" }
    ]
  },
  {
    title: "🎮 games",
    tags: [
      { emoji: "🎯", label: "BGMI / PUBG" },
      { emoji: "🔥", label: "Valorant" },
      { emoji: "🟢", label: "Minecraft" },
      { emoji: "👑", label: "GTA V" },
      { emoji: "🎮", label: "Call of Duty" },
      { emoji: "⚽", label: "EA FC / FIFA" },
      { emoji: "🏆", label: "Counter-Strike 2" },
      { emoji: "🕹️", label: "Fortnite" },
      { emoji: "🌍", label: "Genshin Impact" },
      { emoji: "🐉", label: "Elden Ring" },
      { emoji: "⚡", label: "Clash Royale" },
      { emoji: "🧱", label: "Clash of Clans" },
      { emoji: "💎", label: "Roblox" },
      { emoji: "🧙", label: "Black Myth: Wukong" },
      { emoji: "🌆", label: "Cyberpunk 2077" },
      { emoji: "🏕️", label: "Red Dead Redemption 2" },
      { emoji: "🏎️", label: "Rocket League" },
      { emoji: "🦸", label: "Spider-Man" },
      { emoji: "⚔️", label: "League of Legends" },
      { emoji: "🥊", label: "Tekken & Fighting" }
    ]
  },
  {
    title: "🏅 sports",
    tags: [
      { emoji: "🏏", label: "Cricket" },
      { emoji: "⚽", label: "Football" },
      { emoji: "🏀", label: "Basketball" },
      { emoji: "🏎️", label: "Formula 1" },
      { emoji: "🏸", label: "Badminton" },
      { emoji: "🎾", label: "Tennis" },
      { emoji: "🏓", label: "Table Tennis" },
      { emoji: "🏊", label: "Swimming" },
      { emoji: "🥋", label: "MMA & Boxing" },
      { emoji: "🏏", label: "Virat Kohli" },
      { emoji: "🏏", label: "MS Dhoni" },
      { emoji: "🏏", label: "Rohit Sharma" },
      { emoji: "⚽", label: "Cristiano Ronaldo" },
      { emoji: "⚽", label: "Lionel Messi" },
      { emoji: "🌈", label: "Neeraj Chopra" },
      { emoji: "🏎️", label: "Max Verstappen" },
      { emoji: "🏎️", label: "Lewis Hamilton" },
      { emoji: "💪", label: "Calisthenics & Gym" },
      { emoji: "🏃", label: "Running & Marathons" },
      { emoji: "🏐", label: "Volleyball" }
    ]
  },
  {
    title: "☕ miscellaneous",
    tags: [
      { emoji: "☕", label: "Coffee & Tea" },
      { emoji: "🍕", label: "Foodie & Street Food" },
      { emoji: "🌇", label: "Sunsets & Beaches" },
      { emoji: "⛰️", label: "Mountains & Nature" },
      { emoji: "🌧️", label: "Rainy Days" },
      { emoji: "👟", label: "Sneakers & Streetwear" },
      { emoji: "💻", label: "Tech & Gadgets" },
      { emoji: "🐾", label: "Pets & Animals" },
      { emoji: "🎬", label: "Marvel & DC" },
      { emoji: "⚡", label: "Anime & Manga" },
      { emoji: "🍿", label: "Movie Nights" },
      { emoji: "🎧", label: "Podcasts" },
      { emoji: "🕯️", label: "Cozy Vibes" },
      { emoji: "🖤", label: "Minimalism" },
      { emoji: "🧩", label: "LEGO & Collectibles" },
      { emoji: "🚀", label: "Space & Astronomy" },
      { emoji: "📸", label: "Pinterest Aesthetic" },
      { emoji: "⌨️", label: "Mechanical Keyboards" },
      { emoji: "🚗", label: "Road Trips" },
      { emoji: "🏛️", label: "History & Trivia" }
    ]
  },
  {
    title: "🎭 arts & entertainment",
    tags: [
      { emoji: "🎬", label: "Movies & Cinema" },
      { emoji: "📺", label: "TV Shows & Series" },
      { emoji: "⚡", label: "Anime" },
      { emoji: "🇰🇷", label: "K-Dramas" },
      { emoji: "📖", label: "Books & Literature" },
      { emoji: "🦸", label: "Marvel Universe" },
      { emoji: "⚡", label: "Harry Potter" },
      { emoji: "☕", label: "Friends & Sitcoms" },
      { emoji: "🏴‍☠️", label: "One Piece & Shonen" },
      { emoji: "🎤", label: "Stand-Up Comedy" },
      { emoji: "🎨", label: "Digital Art & Design" },
      { emoji: "🚀", label: "Sci-Fi & Fantasy" },
      { emoji: "👻", label: "Horror & Thrillers" },
      { emoji: "🎙️", label: "Podcasts & Vlogs" },
      { emoji: "🎟️", label: "Live Concerts" },
      { emoji: "🎭", label: "Theatre & Arts" },
      { emoji: "📜", label: "Documentaries" },
      { emoji: "🪄", label: "Studio Ghibli" },
      { emoji: "👽", label: "Stranger Things" },
      { emoji: "🧪", label: "Breaking Bad & Dramas" }
    ]
  }
];
