export const INTERESTS_BY_CATEGORY = [
  {
    title: "❤️ hobbies",
    tags: [
      { emoji: "📚", label: "Reading" },
      { emoji: "✍️", label: "Writing" },
      { emoji: "📸", label: "Photography" },
      { emoji: "🎥", label: "Videography" },
      { emoji: "🎬", label: "Content Creation" },
      { emoji: "🎨", label: "Graphic Design" },
      { emoji: "✏️", label: "Drawing & Sketching" },
      { emoji: "🖌️", label: "Painting" },
      { emoji: "🧵", label: "DIY & Crafts" },
      { emoji: "🖋️", label: "Calligraphy" },
      { emoji: "🍳", label: "Cooking" },
      { emoji: "🧁", label: "Baking" },
      { emoji: "☕", label: "Coffee Brewing" },
      { emoji: "🌱", label: "Gardening" },
      { emoji: "🪴", label: "Plant Care" },
      { emoji: "✈️", label: "Traveling" },
      { emoji: "🥾", label: "Hiking & Trekking" },
      { emoji: "🏕️", label: "Camping" },
      { emoji: "🚗", label: "Road Trips" },
      { emoji: "🐦", label: "Bird Watching" },
      { emoji: "🔭", label: "Stargazing" },
      { emoji: "🏋️", label: "Gym" },
      { emoji: "🏃", label: "Running" },
      { emoji: "🚴", label: "Cycling" },
      { emoji: "🏊", label: "Swimming" },
      { emoji: "🧘", label: "Yoga" },
      { emoji: "🧠", label: "Meditation" },
      { emoji: "💃", label: "Dancing" },
      { emoji: "🎤", label: "Singing" },
      { emoji: "🎸", label: "Playing Musical Instruments" },
      { emoji: "🎛️", label: "Music Production" },
      { emoji: "♟️", label: "Chess" },
      { emoji: "🎲", label: "Board Games" },
      { emoji: "🧩", label: "Puzzle Solving" },
      { emoji: "🪙", label: "Collecting" },
      { emoji: "👗", label: "Fashion & Styling" },
      { emoji: "🛍️", label: "Thrifting" },
      { emoji: "🤝", label: "Volunteering" },
      { emoji: "🐾", label: "Pet Care" },
      { emoji: "💻", label: "Coding" },
      { emoji: "🔌", label: "Electronics & DIY Tech" },
      { emoji: "🤖", label: "Robotics" },
      { emoji: "🕹️", label: "Game Development" },
      { emoji: "🖨️", label: "3D Printing" },
      { emoji: "🌐", label: "Blogging" },
      { emoji: "🎙️", label: "Podcasting" },
      { emoji: "📓", label: "Journaling" },
      { emoji: "🛋️", label: "Home Decor" },
      { emoji: "🏡", label: "Interior Design" },
      { emoji: "🚀", label: "Entrepreneurship" }
    ]
  },
  {
    title: "🎵 music",
    tags: [
      { emoji: "🎤", label: "Arijit Singh" },
      { emoji: "🎶", label: "Pop" },
      { emoji: "🎧", label: "AP Dhillon" },
      { emoji: "🎸", label: "Rock" },
      { emoji: "🎙️", label: "Shreya Ghoshal" },
      { emoji: "🎵", label: "Hip-Hop" },
      { emoji: "🎼", label: "KK" },
      { emoji: "🌙", label: "Lo-fi" },
      { emoji: "🔥", label: "Diljit Dosanjh" },
      { emoji: "🎹", label: "Classical" },
      { emoji: "🌟", label: "Armaan Malik" },
      { emoji: "🎷", label: "Indie" },
      { emoji: "🎧", label: "Atif Aslam" },
      { emoji: "⚡", label: "EDM" },
      { emoji: "💿", label: "Karan Aujla" },
      { emoji: "🎺", label: "R&B" },
      { emoji: "👑", label: "King" },
      { emoji: "🪘", label: "Punjabi" },
      { emoji: "🎭", label: "Seedhe Maut" },
      { emoji: "🎬", label: "Bollywood" },
      { emoji: "🚀", label: "Divine" },
      { emoji: "🎸", label: "Rock Ballads" },
      { emoji: "💥", label: "Emiway Bantai" },
      { emoji: "💜", label: "K-Pop" },
      { emoji: "🌼", label: "Anuv Jain" },
      { emoji: "🎺", label: "Jazz" },
      { emoji: "🤍", label: "Prateek Kuhad" },
      { emoji: "🤠", label: "Country" },
      { emoji: "☀️", label: "Mohit Chauhan" },
      { emoji: "🥁", label: "Metal" },
      { emoji: "🎻", label: "Vishal Mishra" },
      { emoji: "🌈", label: "A.R. Rahman" },
      { emoji: "🎥", label: "Pritam" },
      { emoji: "🎪", label: "Shankar–Ehsaan–Loy" },
      { emoji: "🎨", label: "Amit Trivedi" },
      { emoji: "💖", label: "Taylor Swift" },
      { emoji: "🌌", label: "The Weeknd" },
      { emoji: "🪩", label: "Coldplay" },
      { emoji: "🌵", label: "Travis Scott" },
      { emoji: "🫰", label: "BTS" },
      { emoji: "🌸", label: "BLACKPINK" },
      { emoji: "🌹", label: "Lana Del Rey" },
      { emoji: "🍂", label: "Ed Sheeran" },
      { emoji: "👟", label: "Kendrick Lamar" },
      { emoji: "🌊", label: "Cigarettes After Sex" },
      { emoji: "🎹", label: "Charlie Puth" },
      { emoji: "🌼", label: "Shawn Mendes" },
      { emoji: "🎤", label: "Dua Lipa" },
      { emoji: "🎧", label: "Sabrina Carpenter" },
      { emoji: "🎙️", label: "Olivia Rodrigo" },
      { emoji: "🎸", label: "Post Malone" },
      { emoji: "🌠", label: "Imagine Dragons" },
      { emoji: "⚡", label: "OneRepublic" },
      { emoji: "🦋", label: "Darshan Raval" },
      { emoji: "💝", label: "Stebin Ben" },
      { emoji: "🪷", label: "B Praak" },
      { emoji: "🎇", label: "Jas Manak" },
      { emoji: "🍁", label: "Sidhu Moose Wala" },
      { emoji: "🌟", label: "Harrdy Sandhu" },
      { emoji: "🧿", label: "Jasleen Royal" },
      { emoji: "🎯", label: "Raftaar" },
      { emoji: "🎤", label: "Neha Kakkar" },
      { emoji: "🎼", label: "Vishal–Shekhar" },
      { emoji: "🎹", label: "Sachin–Jigar" },
      { emoji: "🎵", label: "Instrumental" }
    ]
  },
  {
    title: "😎 chill",
    tags: [
      { emoji: "🌍", label: "Adventurous" },
      { emoji: "😂", label: "Funny" },
      { emoji: "🧠", label: "Overthinker" },
      { emoji: "🎨", label: "Creative" },
      { emoji: "🌙", label: "Introvert" },
      { emoji: "💪", label: "Confident" },
      { emoji: "🤪", label: "Goofy" },
      { emoji: "☀️", label: "Extrovert" },
      { emoji: "💡", label: "Open Minded" },
      { emoji: "🥳", label: "Social Butterfly" },
      { emoji: "😌", label: "Laid Back" },
      { emoji: "🎯", label: "Locked In" },
      { emoji: "🌸", label: "Softie" },
      { emoji: "🫂", label: "Caring" },
      { emoji: "🔥", label: "Highkey" },
      { emoji: "🤠", label: "Chaotic" },
      { emoji: "🌈", label: "Optimistic" },
      { emoji: "📸", label: "Main Character" },
      { emoji: "👂", label: "Good Listener" },
      { emoji: "🧃", label: "Go With The Flow" },
      { emoji: "🚀", label: "Ambitious" },
      { emoji: "🥶", label: "Nonchalant" },
      { emoji: "💬", label: "Talkative" },
      { emoji: "🌱", label: "Humble" },
      { emoji: "🎮", label: "Competitive" },
      { emoji: "🤍", label: "Golden Retriever Energy" },
      { emoji: "🌼", label: "Sunshine Energy" },
      { emoji: "🎀", label: "Kind" },
      { emoji: "😏", label: "Sarcastic" },
      { emoji: "💤", label: "Homebody" },
      { emoji: "🌟", label: "Charismatic" },
      { emoji: "🖤", label: "Black Cat Energy" },
      { emoji: "⚖️", label: "Ambivert" },
      { emoji: "🎈", label: "Playful" },
      { emoji: "🪄", label: "Imaginative" },
      { emoji: "🧩", label: "Curious" },
      { emoji: "💎", label: "Genuine" },
      { emoji: "🛋️", label: "Cozy Vibes" },
      { emoji: "🎉", label: "Party Animal" },
      { emoji: "🥹", label: "Sensitive" },
      { emoji: "🎭", label: "Expressive" },
      { emoji: "🌊", label: "Easygoing" },
      { emoji: "🤫", label: "Mysterious" },
      { emoji: "🫶", label: "Sweet" },
      { emoji: "🌿", label: "Lowkey" },
      { emoji: "💀", label: "Unhinged" },
      { emoji: "🎲", label: "Spontaneous" },
      { emoji: "🍃", label: "Free Spirit" },
      { emoji: "🦥", label: "Lazy" },
      { emoji: "🫡", label: "Reliable" },
      { emoji: "💬", label: "Yapper" },
      { emoji: "🌃", label: "Night Owl" },
      { emoji: "📚", label: "Nerd" },
      { emoji: "😇", label: "Wholesome" },
      { emoji: "🎯", label: "Focused" },
      { emoji: "🌅", label: "Early Bird" },
      { emoji: "✨", label: "Dreamer" },
      { emoji: "⚡", label: "Energetic" },
      { emoji: "😈", label: "Menace" },
      { emoji: "🤝", label: "Loyal" },
      { emoji: "🌠", label: "Visionary" },
      { emoji: "🎉", label: "Outgoing" },
      { emoji: "🧘", label: "Calm" },
      { emoji: "🐾", label: "Independent" }
    ]
  },
  {
    title: "🎮 games",
    tags: [
      { emoji: "🟢", label: "Minecraft" },
      { emoji: "🎯", label: "BGMI" },
      { emoji: "🐉", label: "Elden Ring" },
      { emoji: "🚗", label: "Rocket League" },
      { emoji: "🔥", label: "Valorant" },
      { emoji: "🌌", label: "Honkai: Star Rail" },
      { emoji: "🧱", label: "Clash of Clans" },
      { emoji: "🏎️", label: "Forza Horizon" },
      { emoji: "🎭", label: "Among Us" },
      { emoji: "👑", label: "GTA V" },
      { emoji: "⚡", label: "Clash Royale" },
      { emoji: "🥷", label: "Ghost of Tsushima" },
      { emoji: "🌟", label: "Brawl Stars" },
      { emoji: "🏏", label: "Cricket 24" },
      { emoji: "🧬", label: "Helldivers 2" },
      { emoji: "🏆", label: "Counter-Strike 2" },
      { emoji: "🐾", label: "Palworld" },
      { emoji: "⚽", label: "EA FC 26" },
      { emoji: "🌊", label: "Sea of Thieves" },
      { emoji: "🛡️", label: "Rainbow Six Siege" },
      { emoji: "🧙", label: "Hogwarts Legacy" },
      { emoji: "🧨", label: "Dota 2" },
      { emoji: "🎮", label: "Call of Duty" },
      { emoji: "🧩", label: "It Takes Two" },
      { emoji: "🌍", label: "Genshin Impact" },
      { emoji: "🥊", label: "Tekken 8" },
      { emoji: "🌿", label: "Stardew Valley" },
      { emoji: "💎", label: "Roblox" },
      { emoji: "🦸", label: "Marvel's Spider-Man" },
      { emoji: "🚀", label: "Marvel Rivals" },
      { emoji: "🏁", label: "Need for Speed" },
      { emoji: "🐺", label: "The Witcher 3" },
      { emoji: "🏝️", label: "Animal Crossing" },
      { emoji: "🧑‍🚀", label: "No Man's Sky" },
      { emoji: "🎖️", label: "Apex Legends" },
      { emoji: "🧪", label: "Resident Evil" },
      { emoji: "🧙", label: "Black Myth: Wukong" },
      { emoji: "👻", label: "Phasmophobia" },
      { emoji: "🌆", label: "Cyberpunk 2077" },
      { emoji: "🏹", label: "PUBG PC" },
      { emoji: "🚚", label: "Euro Truck Simulator 2" },
      { emoji: "🐉", label: "Dragon Ball: Sparking! ZERO" },
      { emoji: "🛠️", label: "Terraria" },
      { emoji: "🥷", label: "Mortal Kombat 1" },
      { emoji: "🏀", label: "NBA 2K" },
      { emoji: "⚔️", label: "League of Legends" },
      { emoji: "🎨", label: "Infinity Nikki" },
      { emoji: "🌠", label: "Wuthering Waves" },
      { emoji: "✈️", label: "Microsoft Flight Simulator" },
      { emoji: "🦊", label: "The Legend of Zelda" },
      { emoji: "🚢", label: "World of Warships" },
      { emoji: "🧟", label: "Dying Light" },
      { emoji: "🌋", label: "Monster Hunter" },
      { emoji: "🐻", label: "Pokémon" },
      { emoji: "🌀", label: "Zenless Zone Zero" },
      { emoji: "🏰", label: "Civilization VII" },
      { emoji: "🪖", label: "Battlefield" },
      { emoji: "🏕️", label: "Red Dead Redemption 2" },
      { emoji: "👊", label: "Street Fighter 6" },
      { emoji: "🏹", label: "Assassin's Creed" },
      { emoji: "💀", label: "DOOM" },
      { emoji: "🎲", label: "Chess" },
      { emoji: "🕹️", label: "Fortnite" },
      { emoji: "🎮", label: "Mobile Gamer" },
      { emoji: "🎼", label: "Game Soundtracks" }
    ]
  },
  {
    title: "🏅 sports",
    tags: [
      { emoji: "🏸", label: "PV Sindhu" },
      { emoji: "⚽", label: "Football" },
      { emoji: "🏏", label: "Virat Kohli" },
      { emoji: "🏀", label: "Basketball" },
      { emoji: "🏎️", label: "Max Verstappen" },
      { emoji: "🏋️", label: "Gym" },
      { emoji: "🏏", label: "MS Dhoni" },
      { emoji: "🎾", label: "Carlos Alcaraz" },
      { emoji: "🥊", label: "Boxing" },
      { emoji: "🏸", label: "Badminton" },
      { emoji: "🏃", label: "Usain Bolt" },
      { emoji: "🏏", label: "Jasprit Bumrah" },
      { emoji: "⚽", label: "Cristiano Ronaldo" },
      { emoji: "🏊", label: "Swimming" },
      { emoji: "🏹", label: "Archery" },
      { emoji: "🏏", label: "Rohit Sharma" },
      { emoji: "🏎️", label: "Formula 1" },
      { emoji: "🏸", label: "Lakshya Sen" },
      { emoji: "🧘", label: "Yoga" },
      { emoji: "⚽", label: "Lionel Messi" },
      { emoji: "🏏", label: "Cricket" },
      { emoji: "🏀", label: "Stephen Curry" },
      { emoji: "🚴", label: "Cycling" },
      { emoji: "🏏", label: "Shubman Gill" },
      { emoji: "🎾", label: "Novak Djokovic" },
      { emoji: "🥋", label: "MMA" },
      { emoji: "🏏", label: "Hardik Pandya" },
      { emoji: "🏸", label: "Saina Nehwal" },
      { emoji: "🏃", label: "Running" },
      { emoji: "🏎️", label: "Lewis Hamilton" },
      { emoji: "🏏", label: "Suryakumar Yadav" },
      { emoji: "⛳", label: "Golf" },
      { emoji: "🥊", label: "Mary Kom" },
      { emoji: "🏐", label: "Volleyball" },
      { emoji: "⚽", label: "Sunil Chhetri" },
      { emoji: "🏏", label: "Sachin Tendulkar" },
      { emoji: "🧗", label: "Rock Climbing" },
      { emoji: "🎾", label: "Rafael Nadal" },
      { emoji: "🏏", label: "Rishabh Pant" },
      { emoji: "🏸", label: "Chirag Shetty" },
      { emoji: "🏏", label: "Yuvraj Singh" },
      { emoji: "🏍️", label: "MotoGP" },
      { emoji: "⚽", label: "Kylian Mbappé" },
      { emoji: "🏓", label: "Table Tennis" },
      { emoji: "🌈", label: "Neeraj Chopra" },
      { emoji: "🏏", label: "KL Rahul" },
      { emoji: "🥾", label: "Trekking" },
      { emoji: "🏎️", label: "Charles Leclerc" },
      { emoji: "🏸", label: "Satwiksairaj Rankireddy" },
      { emoji: "🏀", label: "LeBron James" },
      { emoji: "🥊", label: "Mike Tyson" },
      { emoji: "🏏", label: "AB de Villiers" },
      { emoji: "🏃", label: "Marathon" },
      { emoji: "🏏", label: "Glenn Maxwell" },
      { emoji: "⚽", label: "Erling Haaland" },
      { emoji: "🚵", label: "Mountain Biking" },
      { emoji: "🏌️", label: "Aditi Ashok" },
      { emoji: "🏏", label: "Ben Stokes" },
      { emoji: "🏎️", label: "Oscar Piastri" },
      { emoji: "🎾", label: "Jannik Sinner" },
      { emoji: "🥋", label: "Khabib Nurmagomedov" },
      { emoji: "🎣", label: "Fishing" },
      { emoji: "⚽", label: "Neymar Jr." },
      { emoji: "🤼", label: "Wrestling" },
      { emoji: "🏇", label: "Horse Riding" },
      { emoji: "🏹", label: "Deepika Kumari" },
      { emoji: "🏀", label: "Michael Jordan" },
      { emoji: "🏓", label: "Manika Batra" },
      { emoji: "⚽", label: "Lamine Yamal" },
      { emoji: "🥊", label: "Oleksandr Usyk" },
      { emoji: "🦈", label: "Michael Phelps" },
      { emoji: "🦅", label: "Conor McGregor" },
      { emoji: "💪", label: "Calisthenics" },
      { emoji: "🎯", label: "Darts" },
      { emoji: "🏏", label: "IPL Fans" }
    ]
  },
  {
    title: "☕ miscellaneous",
    tags: [
      { emoji: "☕", label: "Coffee Lover" },
      { emoji: "🍵", label: "Matcha Lover" },
      { emoji: "🧋", label: "Bubble Tea" },
      { emoji: "🍕", label: "Pizza Lover" },
      { emoji: "🍔", label: "Burger Lover" },
      { emoji: "🍟", label: "Fries Lover" },
      { emoji: "🍜", label: "Ramen Lover" },
      { emoji: "🍣", label: "Sushi Lover" },
      { emoji: "🌮", label: "Street Food" },
      { emoji: "🌶️", label: "Spicy Food" },
      { emoji: "🍫", label: "Sweet Tooth" },
      { emoji: "🍦", label: "Ice Cream" },
      { emoji: "🥤", label: "Cold Coffee" },
      { emoji: "🧃", label: "Fresh Juices" },
      { emoji: "🌅", label: "Sunrise" },
      { emoji: "🌇", label: "Sunsets" },
      { emoji: "🌧️", label: "Rainy Days" },
      { emoji: "❄️", label: "Winter" },
      { emoji: "☀️", label: "Summer" },
      { emoji: "🍂", label: "Autumn" },
      { emoji: "🏖️", label: "Beaches" },
      { emoji: "⛰️", label: "Mountains" },
      { emoji: "🌲", label: "Nature" },
      { emoji: "🌌", label: "Stargazing" },
      { emoji: "✈️", label: "Travel" },
      { emoji: "🚗", label: "Road Trips" },
      { emoji: "🗺️", label: "Exploring" },
      { emoji: "🎡", label: "Theme Parks" },
      { emoji: "🏕️", label: "Camping" },
      { emoji: "🛍️", label: "Shopping" },
      { emoji: "👟", label: "Sneakers" },
      { emoji: "👕", label: "Streetwear" },
      { emoji: "🕶️", label: "Fashion" },
      { emoji: "🎒", label: "Backpacks" },
      { emoji: "🎨", label: "Pinterest" },
      { emoji: "📸", label: "Aesthetic Photography" },
      { emoji: "🎞️", label: "Film Photography" },
      { emoji: "📚", label: "Libraries" },
      { emoji: "💻", label: "Tech Enthusiast" },
      { emoji: "⌨️", label: "Mechanical Keyboards" },
      { emoji: "🖥️", label: "PC Setup" },
      { emoji: "📱", label: "Gadgets" },
      { emoji: "🎬", label: "Marvel" },
      { emoji: "🦇", label: "DC" },
      { emoji: "⚡", label: "Harry Potter" },
      { emoji: "🪄", label: "Studio Ghibli" },
      { emoji: "🎌", label: "Anime" },
      { emoji: "📖", label: "Manga" },
      { emoji: "🇰🇷", label: "K-Dramas" },
      { emoji: "🎭", label: "Sitcoms" },
      { emoji: "🎧", label: "Podcasts" },
      { emoji: "📺", label: "Netflix" },
      { emoji: "🍿", label: "Movie Nights" },
      { emoji: "🎫", label: "Live Concerts" },
      { emoji: "🎪", label: "Live Events" },
      { emoji: "🌱", label: "Plant Parent" },
      { emoji: "🐶", label: "Dog Lover" },
      { emoji: "🐱", label: "Cat Lover" },
      { emoji: "🐠", label: "Aquarium" },
      { emoji: "🕯️", label: "Cozy Vibes" },
      { emoji: "🖤", label: "Minimalist" },
      { emoji: "🏛️", label: "Dark Academia" },
      { emoji: "🌿", label: "Cottagecore" },
      { emoji: "🌸", label: "Cherry Blossoms" },
      { emoji: "🎁", label: "Collectibles" },
      { emoji: "🧩", label: "LEGO" },
      { emoji: "🚀", label: "Space" },
      { emoji: "🌍", label: "Geography" },
      { emoji: "🏛️", label: "History" },
      { emoji: "🔬", label: "Science" },
      { emoji: "💡", label: "Innovation" },
      { emoji: "🌎", label: "Sustainability" },
      { emoji: "🏞️", label: "National Parks" },
      { emoji: "🎆", label: "Fireworks" },
      { emoji: "🎈", label: "Festivals" }
    ]
  },
  {
    title: "🎭 arts & entertainment",
    tags: [
      { emoji: "🎬", label: "Movies" },
      { emoji: "🎭", label: "Theatre" },
      { emoji: "🎞️", label: "Short Films" },
      { emoji: "🎥", label: "Filmmaking" },
      { emoji: "🍿", label: "Movie Nights" },
      { emoji: "🎨", label: "Digital Art" },
      { emoji: "✏️", label: "Sketching" },
      { emoji: "🖌️", label: "Painting" },
      { emoji: "🏺", label: "Pottery" },
      { emoji: "🧵", label: "DIY Crafts" },
      { emoji: "✂️", label: "Origami" },
      { emoji: "📖", label: "Books" },
      { emoji: "📚", label: "Fiction" },
      { emoji: "📜", label: "Non-Fiction" },
      { emoji: "✍️", label: "Poetry" },
      { emoji: "📓", label: "Journaling" },
      { emoji: "📖", label: "Manga" },
      { emoji: "💥", label: "Comics" },
      { emoji: "📺", label: "TV Shows" },
      { emoji: "🇰🇷", label: "K-Dramas" },
      { emoji: "⚡", label: "Anime" },
      { emoji: "🎌", label: "Studio Ghibli" },
      { emoji: "🦸", label: "Marvel" },
      { emoji: "🦇", label: "DC" },
      { emoji: "⚡", label: "Harry Potter" },
      { emoji: "🪄", label: "Percy Jackson" },
      { emoji: "🌌", label: "Star Wars" },
      { emoji: "🧙", label: "The Lord of the Rings" },
      { emoji: "⚔️", label: "Game of Thrones" },
      { emoji: "🕵️", label: "Sherlock" },
      { emoji: "👽", label: "Stranger Things" },
      { emoji: "🧪", label: "Breaking Bad" },
      { emoji: "💼", label: "Suits" },
      { emoji: "👑", label: "Peaky Blinders" },
      { emoji: "🏝️", label: "The Office" },
      { emoji: "☕", label: "Friends" },
      { emoji: "🟡", label: "How I Met Your Mother" },
      { emoji: "🧠", label: "Black Mirror" },
      { emoji: "🏴‍☠️", label: "One Piece" },
      { emoji: "🍥", label: "Naruto" },
      { emoji: "👹", label: "Demon Slayer" },
      { emoji: "⚔️", label: "Attack on Titan" },
      { emoji: "👊", label: "Jujutsu Kaisen" },
      { emoji: "🏐", label: "Haikyuu!!" },
      { emoji: "🥷", label: "Solo Leveling" },
      { emoji: "👻", label: "Death Note" },
      { emoji: "🧬", label: "Chainsaw Man" },
      { emoji: "🕶️", label: "Spy × Family" },
      { emoji: "🎭", label: "Cosplay" },
      { emoji: "🎤", label: "Stand-Up Comedy" },
      { emoji: "😂", label: "Memes" },
      { emoji: "🎙️", label: "Podcasts" },
      { emoji: "📹", label: "YouTube" },
      { emoji: "🎥", label: "Vlogging" },
      { emoji: "📸", label: "Photography" },
      { emoji: "🎨", label: "Illustration" },
      { emoji: "🖋️", label: "Calligraphy" },
      { emoji: "🧩", label: "Storytelling" },
      { emoji: "🎬", label: "Documentaries" },
      { emoji: "🌍", label: "Travel Documentaries" },
      { emoji: "🚀", label: "Sci-Fi" },
      { emoji: "🕵️", label: "Mystery" },
      { emoji: "💘", label: "Romance" },
      { emoji: "👻", label: "Horror" },
      { emoji: "🤣", label: "Comedy" },
      { emoji: "⚔️", label: "Action" },
      { emoji: "🌟", label: "Fantasy" },
      { emoji: "🧠", label: "Psychological Thrillers" },
      { emoji: "🌿", label: "Slice of Life" },
      { emoji: "🪐", label: "Space & Astronomy" },
      { emoji: "🏛️", label: "History" },
      { emoji: "🔬", label: "Science" },
      { emoji: "🎟️", label: "Live Shows" },
      { emoji: "🎪", label: "Musicals" },
      { emoji: "🎨", label: "Art Galleries" }
    ]
  }
];
