export const categoriesList = [
  { id: 'all', label: 'All', icon: '✨' },
  { id: 'technology', label: 'Technology', icon: '💻' },
  { id: 'programming', label: 'Programming', icon: '👨‍💻' },
  { id: 'ai', label: 'Artificial Intelligence', icon: '🤖' },
  { id: 'design', label: 'Design', icon: '🎨' },
  { id: 'art', label: 'Art', icon: '🖌️' },
  { id: 'startup', label: 'Business & Startups', icon: '💼' },
  { id: 'science', label: 'Science', icon: '🔬' },
  { id: 'engineering', label: 'Engineering', icon: '⚙️' },
  { id: 'academics', label: 'Academics', icon: '📚' },
  { id: 'career', label: 'Career', icon: '💼' },
  { id: 'gaming', label: 'Gaming', icon: '🎮' },
  { id: 'anime', label: 'Anime & Manga', icon: '🌸' },
  { id: 'memes', label: 'Memes & Humor', icon: '😂' },
  { id: 'music', label: 'Music', icon: '🎵' },
  { id: 'photography', label: 'Photography', icon: '📸' },
  { id: 'videography', label: 'Videography', icon: '🎥' },
  { id: 'movies', label: 'Movies & TV', icon: '🎬' },
  { id: 'sports', label: 'Sports', icon: '⚽' },
  { id: 'fitness', label: 'Fitness', icon: '💪' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'food', label: 'Food', icon: '🍕' },
  { id: 'fashion', label: 'Fashion', icon: '👗' },
  { id: 'books', label: 'Books & Literature', icon: '📖' },
  { id: 'pets', label: 'Pets & Animals', icon: '🐶' },
  { id: 'volunteering', label: 'Volunteering', icon: '🤝' },
  { id: 'campus', label: 'Campus Life', icon: '🎓' },
  { id: 'entrepreneurship', label: 'Entrepreneurship', icon: '🚀' },
  { id: 'content', label: 'Content Creation', icon: '🎥' },
  { id: 'languages', label: 'Languages', icon: '🌍' },
  { id: 'health', label: 'Health & Wellness', icon: '🩺' },
  { id: 'lifestyle', label: 'Lifestyle', icon: '🌿' },
  { id: 'other', label: 'Other', icon: '✨' },
];
